phases:
  - duration: 30    # seconds
    damage: 0
  - duration: 20
    damage: 1
  - duration: 15
    damage: 2
  - duration: 10
    damage: 4
  - duration:  8
    damage: 8
  - duration:  5
    damage: 16
