# config/storm.yaml

phases:
  - hold:   500    # seconds to stay stationary
    shrink: 30     # seconds to transition to next radius
    damage: 0
  - hold:   400
    shrink: 15
    damage: 1
  - hold:   300
    shrink: 15
    damage: 2
